/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SS_aliases.h"
#include "SS.h"
#include "SPI.h"
#include "SPI_PVT.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "MOSI_aliases.h"
#include "MOSI.h"
#include "MISO_aliases.h"
#include "MISO.h"
#include "DISP_RST_aliases.h"
#include "DISP_RST.h"
#include "DMA_Tx_dma.h"
#include "DISP_BCKL_aliases.h"
#include "DISP_BCKL.h"
#include "DISP_DC_aliases.h"
#include "DISP_DC.h"
#include "UART.h"
#include "UART_PVT.h"
#include "isr_SPI_TX_DMA.h"
#include "isr_SPI_TX.h"
#include "LED_aliases.h"
#include "LED.h"
#include "QuadDec_SW_aliases.h"
#include "QuadDec_SW.h"
#include "QuadDec.h"
#include "Clock_1.h"
#include "A_aliases.h"
#include "A.h"
#include "B_aliases.h"
#include "B.h"
#include "PWM_Tren.h"
#include "PWM_Base.h"
#include "Clk.h"
#include "TXgate_aliases.h"
#include "TXgate.h"
#include "Control.h"
#include "Rx_gate_aliases.h"
#include "Rx_gate.h"
#include "SPI_IntClock.h"
#include "QuadDec_Cnt8.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

